name = "web-zakynthos"
compatibility_date = "2026-06-10"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "TRIP_DB"
database_name = "zakynthos-trip"
database_id = "01f8346d-2fe1-4f65-bfc4-b0af7a12a440"
